# Generated by Django 6.0.5 on 2026-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
