# Generated by Django 6.0.5 on 2026-06-17 10:14

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_accounts_to_customuser_and_profiles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
