# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_coursevideo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentEnrollment",
            new_name="Enrollment",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
